export const EventCodes =
{
    Leave: 1,
    Move: 3,
    NewPlayer: 27,
    NewSimpleHarvestableObject: 36,
    NewSimpleHarvestableObjectList: 37,
    NewHarvestableObject: 38,
    HarvestableChangeState: 44,
    MobChangeState: 45,
    HarvestFinished: 59,
    Respawn: 85,
    RegenerationHealthChanged: 88,
    CharacterEquipmentChanged: 87,
    NewTreasureChest: 114,
    NewMob: 120,
    Mounted: 203,
    MountStart: 204,
    MountCancel: 205,
    NewRandomDungeon: 311,
    FishingFinished: 344,
    NewFishingZoneObject: 347,
    NewLootChest: 380,
    NewMistsCagedWisp: 517,
    MistsWispCageOpened: 518,
}